pipeline {
  agent any
  options { timestamps(); skipDefaultCheckout(true) }
  tools { jdk 'JDK21' }

  parameters {
    booleanParam(name: 'RUN_IT', defaultValue: false, description: 'Run integration tests')
  }

  environment {
    MAVEN_OPTS = "-Dmaven.repo.local=.m2/repository"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build, Test & Verify') {
      steps {
		dir('RRS') {
        	script {
          		if (params.RUN_IT) {
            		bat 'mvn -B clean verify -DskipITs=false -Dspring.profiles.active=test'
          		} else {
           		 bat 'mvn -B clean verify -DskipITs=true -Dspring.profiles.active=test'
          		}		
        	}
        }
      }
    }

    stage('SonarQube Analysis') {
      steps {
        withSonarQubeEnv('LocalSonar') {
          bat 'mvn -B sonar:sonar -Dsonar.projectKey=recipe-recommendation-system -Dsonar.projectName="Recipe Recommendation System"'
        }
      }
    }

    stage('Quality Gate') {
      steps {
        timeout(time: 2, unit: 'MINUTES') {
          waitForQualityGate abortPipeline: true
        }
      }
    }
  }

  post {
    always {
      junit testResults: '**/target/surefire-reports/*.xml, **/target/failsafe-reports/*.xml', allowEmptyResults: true

      archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true

      publishHTML(target: [
        reportDir: 'target/site/jacoco',
        reportFiles: 'index.html',
        reportName: 'JaCoCo Code Coverage',
        keepAll: true,
        alwaysLinkToLastBuild: true,
        allowMissing: true
      ])

      publishHTML(target: [
        reportDir: 'target/karate-reports',
        reportFiles: 'karate-summary.html',
        reportName: 'Karate Report',
        keepAll: true,
        alwaysLinkToLastBuild: true,
        allowMissing: true
      ])
    }
  }
}